services:
  - type: web
    name: ghostshell-license-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ghostshell-licenses-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_TOKEN
        generateValue: true
      - key: UNIVERSAL_LICENSE_KEY
        value: GHOST-SHELL-UNIVERSAL-2024
      - key: PYTHON_VERSION
        value: 3.11.7   # ✅ force a safe version with wheels
