services:
  - type: web
    name: ghostshell-license-server
    env: python
    plan: free
    buildCommand: |
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      source $HOME/.cargo/env
      pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DATABASE_URL
        fromDatabase:
          name: ghostshell-licenses-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_TOKEN
        generateValue: true
      - key: UNIVERSAL_LICENSE_KEY
        value: GHOST-SHELL-UNIVERSAL-2024
      - key: PORT
        value: 10000
  - type: static
    name: ghostshell-license-frontend
    env: static
    plan: free
    buildCommand: npm run build
    publishPath: frontend/build
    envVars:
      - key: NODE_VERSION
        value: 18
databases:
  - name: ghostshell-licenses-db
    databaseName: ghostshell_licenses
    user: ghostshell_admin
