services:
  - type: web
    name: ghostshell-license-server
    env: python
    buildCommand: pip install .
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ghostshell-licenses-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_TOKEN
        generateValue: true
      - key: UNIVERSAL_LICENSE_KEY
        value: GHOST-SHELL-UNIVERSAL-2024
      - key: PYTHON_VERSION
        value: 3.11.7   # ✅ ensures wheels instead of maturin builds

databases:
  - name: ghostshell-licenses-db
    databaseName: ghostshell_licenses
    user: ghostshell_admin
